Change color intent
ChristopherRogers1991/mycroft-hue pull request #27
Opened 2018-08-24 09:54 UTC by alueck

Implements the ability to change the light colors. I did only test it using the Mycroft CLI and english language, so it would be nice, if some other people could also test it, before it being merged.

I added a few basic colors, but especially white needs a lot more distinction between different color temperatures.

2018-08-24 10:05 UTC, ChristopherRogers1991 commented
Hello Adrian,

Thank you for your contribution! I'm currently on vacation, but I'll try to
take a look at this some time next week.

Thanks,

Chris


On Fri, Aug 24, 2018, 9:54 AM Adrian Lück <notifications@github.com> wrote:

> Implements the ability to change the light colors. I did only test it
> using the Mycroft CLI and english language, so it would be nice, if some
> other people could also test it, before it being merged.
>
> I added a few basic colors, but especially white needs a lot more
> distinction between different color temperatures.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ChristopherRogers1991/mycroft-hue/pull/27
> Commit Summary
>
>    - Add change color intent
>    - Add file based language dependent color definitions
>    - Remove hard coded color change
>    - Change mapping of colors so rgb values have to be provided only in
>    one file
>    - Add some basic colors
>    - Merge pull request #1 from alueck/feature/change-color
>
> File Changes
>
>    - *M* __init__.py
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-0>
>    (91)
>    - *A* colors/color-definitions.json
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-1>
>    (11)
>    - *A* colors/de-colors.json
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-2>
>    (11)
>    - *A* dialog/de-de/change.color.dialog
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-3>
>    (2)
>    - *A* dialog/de-de/color.not.found.dialog
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-4>
>    (1)
>    - *A* dialog/en-us/change.color.dialog
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-5>
>    (2)
>    - *A* dialog/en-us/color.not.found.dialog
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-6>
>    (1)
>    - *A* vocab/de-de/ColorKeyword.voc
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-7>
>    (1)
>    - *A* vocab/en-us/ColorKeyword.voc
>    <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27/files#diff-8>
>    (1)
>
> Patch Links:
>
>    - https://github.com/ChristopherRogers1991/mycroft-hue/pull/27.patch
>    - https://github.com/ChristopherRogers1991/mycroft-hue/pull/27.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ChristopherRogers1991/mycroft-hue/pull/27>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AINZv_ju3MLnwe3z4nzL_TObTW9wqrQvks5uT81pgaJpZM4WLEsM>
> .
>

2018-08-31 20:21 UTC, ChristopherRogers1991 requested changes
Hey @alueck,

Sincere apologies for the slow response on this - I was on vacation last week, and am currently traveling for work (having to do this review on a tiny chromebook).

Thank you very much for the contribution! I've looked over the code and left a few comments for what I think could improve this a bit. Please look them over, and let me know what you think. Feel free to push back if you disagree strongly with anything, and we can continue to iterate and discuss.

Thanks again,

Chris

2018-09-12 17:18 UTC, alueck commented
Hi @ChristopherRogers1991,

sorry for the late response, but I did not receive an email about you comment. I like your suggestions, but I am actually not using Mycroft anymore, because it did not fit my needs. However, I might still implement them (probably this weekend), if I find some time. Otherwise feel free to implement it yourself based on my code.

2018-09-12 18:43 UTC, ChristopherRogers1991 commented
Hey @alueck,

Thanks for the note. Due to some work related travels, it'll be at least a few works before I would be able to implement the changes, but I'm happy to leave this PR open indefinitely, and I'm sure at some point you or I or someone else will pick it up and finish it out.

Just out of curiosity, can I ask what your use case is, and where Mycroft fell short? (I'm particularly curious to know if it was due to shortcomings in this plugin.)

2018-09-12 19:05 UTC, alueck commented
The main problem I had with Mycroft was the speech recognition if there was some background noise (e.g. watching TV). The microphone still seemed to pick up my voice loud enough based on the level display of the Mycroft CLI, but did not even recognize that I said the hotword. 

My main use case was controlling my Hue lights, which worked pretty well with this plugin. I like the fact, that it controls the lights over your local network. And it is really nice that it is open source and therefore allows everybody to contribute or tailor it to their likings. My fork actually contains another extension for grouping lights with the same name together ([see here, if interested](https://github.com/alueck/mycroft-hue/tree/feature/register-lights-by-name)), so that I could control my floor lamp with two Hue lights by just saying "Turn the floor lamp on" . This just had the disadvantage that I could not distinguish the lights in the app by just looking at the name.

2025-06-05 18:07 UTC, closed without merging